"""Add player_id to PlayerStock

Revision ID: 8567876b382b
Revises: da5f62cdfe0c
Create Date: 2024-11-17 06:17:08.260900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8567876b382b'
down_revision = 'da5f62cdfe0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('player_stock', schema=None) as batch_op:
    batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
    batch_op.create_unique_constraint('uq_player_stock_player_id', ['player_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
