"""describe your changes here

Revision ID: da5f62cdfe0c
Revises: 
Create Date: 2024-11-17 05:38:19.425834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5f62cdfe0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('player_stock', sa.Column('player_id', sa.Integer(), unique=True, nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stock_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_stock_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['player_stock_id'], ['player_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
